name: Pull Request Checks
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: format check
        run: pnpm format:check
      - name: lint check
        run: pnpm lint:check
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: test
        run: pnpm test
      # - name: Uploading to codecov.io
      #   run: npx codecov
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  test-doc:
    name: "Test Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: run doc
        run: pnpm doc
      - name: check if diff
        run: git diff --exit-code || exit 1
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
